### ISSUE TITLE
need an iOS version

### ISSUE THREAD

**Issue by teriiehina** [ChristopheCVB/CanadaYPClient#1]
the code you commited is only for android. how do you plan to provide this only with java code ?

**Comment by ChristopheCVB** [comment]
Do you want to join the project to code the iOS part ?

**Comment by teriiehina** [comment]
how dare you close that without any discussion with the community ???

**Comment by ChristopheCVB** [comment]
Ahah ! And that's not true, I asked you if you want to implement the iOS part... Anyway, it's an Android App repository, so I guess I'll leave that closed :)

PS : Stop trolling Peter ;)

**Comment by teriiehina** [comment]
:trollface:
